(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function l(a){l[" "](a);return a}l[" "]=function(){};var m={},n=null;var aa="function"===typeof Uint8Array;const p=Symbol(void 0);function q(a){Object.isFrozen(a)||(p?a[p]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function r(a){return null!==a&&"object"===typeof a&&a.constructor===Object};function t(a,b){if(null!=a)return Array.isArray(a)||r(a)?u(a,b):b(a)}function u(a,b){if(Array.isArray(a)){var c=Array(a.length);for(let e=0;e<a.length;e++)c[e]=t(a[e],b);if(b=Array.isArray(a)){var d;p?d=a[p]:d=a.g;b=(null==d?0:d)&1}b&&q(c);return c}d={};for(c in a)d[c]=t(a[c],b);return d}
function ba(a){a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(aa&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!n){n={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}b=m[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var v=a[f],w=a[f+
1];k=a[f+2];h=b[v>>2];v=b[(v&3)<<4|w>>4];w=b[(w&15)<<2|k>>6];k=b[k&63];c[e++]=h+v+w+k}h=0;k=d;switch(a.length-f){case 2:h=a[f+1],k=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}a=c.join("")}}return a};let x;function y(a,b,c){var d=x;x=null;a||(a=d);d=this.constructor.u;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.s||0);this.l=null;this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],r(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=null):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.j?(a+=this.i,(d=this.g[a])?Array.isArray(d)&&q(d):this.g[a]=z):(d=this.j+this.i,this.g[d]||(this.h=this.g[d]={}),(d=this.h[a])?Array.isArray(d)&&q(d):
this.h[a]=z)}const z=Object.freeze(q([]));function A(a,b,c=!1){return-1===b?null:c||b>=a.j?a.h?a.h[b]:void 0:a.g[b+a.i]}function ca(a){a=A(a,2);return null==a?0:a}function da(a){a=A(a,16);a=null==a?a:!!a;return null==a?!1:a}function B(a,b,c){if(-1===c)return null;a.l||(a.l={});const d=a.l[c];if(d)return d;let e=A(a,c,!1);if(null==e)return d;b=new b(e);return a.l[c]=b}y.prototype.toJSON=function(){return u(this.g,ba)};y.prototype.toString=function(){return this.g.toString()};var fa=class extends y{constructor(a){super(a,-1,ea)}},ea=[17];var ia=class extends y{constructor(a){super(a,-1,ha)}},ha=[27];var ja=class extends y{constructor(){super(C)}};var D=document;/*

 SPDX-License-Identifier: Apache-2.0
*/
function E(){var a=F;try{var b;if(b=!!a&&null!=a.location.href)a:{try{l(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function ka(a){var b={stack:Error().stack};for(const c in b)Object.prototype.hasOwnProperty.call(b,c)&&a.call(void 0,b[c],c,b)}let G=[];const H=()=>{const a=G;G=[];for(const b of a)try{b()}catch(c){}};
var la=a=>{var b=window;"complete"===b.document.readyState?(G.push(a),1==G.length&&(window.Promise?Promise.resolve().then(H):window.setImmediate?setImmediate(H):setTimeout(H,0))):b.addEventListener("load",a)};var na=()=>{let a="https://pagead2.googlesyndication.com/pagead/gen_204?id=badpubwin";ka((b,c)=>{b&&(a+=`&${c}=${encodeURIComponent(b)}`)});ma(a)},ma=a=>{var b=window;if(b.fetch)b.fetch(a,{keepalive:!0,credentials:"include",redirect:"follow",method:"get",mode:"no-cors"});else{b.google_image_requests||(b.google_image_requests=[]);var c=b.document;c=void 0===c?document:c;c=c.createElement("img");c.src=a;b.google_image_requests.push(c)}};var I=!!window.google_async_iframe_id;let F=I&&window.parent||window;let J=null;var K=()=>{const a=g.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},L=()=>{const a=g.performance;return a&&a.now?a.now():null};class oa{constructor(a,b){var c=L()||K();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const M=g.performance,pa=!!(M&&M.mark&&M.measure&&M.clearMarks),N=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=pa){var b;if(null===J){J="";try{a="";try{a=g.top.location.hash}catch(c){a=g.location.hash}a&&(J=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=J;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function qa(a){a&&M&&N()&&(M.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),M.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))}
class ra{constructor(){var a=O;this.g=[];this.i=a||g;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.g=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.h=N()||(null!=b?b:1>Math.random())}start(a,b){if(!this.h)return null;a=new oa(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;M&&N()&&M.mark(b);return a}end(a){if(this.h&&"number"===typeof a.value){a.duration=(L()||K())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;M&&N()&&M.mark(b);!this.h||2048<this.g.length||
this.g.push(a)}}};if(I&&!E()){.01>Math.random()&&na();let a="."+D.domain;try{for(;2<a.split(".").length&&!E();)D.domain=a=a.substr(a.indexOf(".")+1),F=window.parent}catch(b){}E()||(F=window)}const O=F,P=new ra;var Q=()=>{O.google_measure_js_timing||(P.h=!1,P.g!=P.i.google_js_reporting_queue&&(N()&&Array.prototype.forEach.call(P.g,qa,void 0),P.g.length=0))};"number"!==typeof O.google_srt&&(O.google_srt=Math.random());
if("complete"==O.document.readyState)Q();else if(P.h){var sa=()=>{Q()},R=O;R.addEventListener&&R.addEventListener("load",sa,!1)};function S(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function T(a,b,c){a.body.addEventListener(b,c)}
var ta=class{constructor(){var a=U;this.body=a;S(a,"sampling_mod");var b=S(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}};function ua({threshold:a,target:b,m:c,o:d}){if(window.IntersectionObserver){var e=!1;(new IntersectionObserver(f=>{0!==f.length&&f[0].isIntersecting&&(!e&&c&&c(),e=!0,d&&d())},{threshold:a})).observe(b)}};var va=class{constructor(){this.g={}}set(a,b){this.g[a]=b}get(a){return this.g[a]}};var wa=class{constructor(){this.channel=1;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}tick(a,b){this.g&&(this.setData(a,Date.now()-window.mys.pingback.getBaseTime()),this.send(b))}};var xa=class{constructor(a){this.context=a;this.i=new va;this.pingback=new wa}g(){}};function ya(){var a=V,b=W,c;2===ca(b)||null!==(c=B(B(b,ia,1),fa,10))&&void 0!==c&&da(c)||(b=mys.engine?mys.engine.stage():0,0===(b&1)&&T(a.context,"overallStart",()=>{}),0!==(b&4)&&a.g.g(),T(a.context,"browserStart",()=>{}),T(a.context,"browserReady",()=>{a.g.g()}),T(a.context,"browserQuiet",()=>{}))}var za=class{constructor(){var a=X;this.g=Y;this.context=a}};var Aa=class extends xa{};function Ba(a){a.h||(a.h=!0,ua({threshold:.9,target:document.querySelector(".x-layout"),m:()=>{const b=document.querySelector(".x-layout");b&&b.classList.add("web-on-show")}}))}var Ca=class extends Aa{constructor(a){super(a);this.h=!1}g(){setTimeout(()=>{la(()=>{Ba(this)})},0)}};var Da=class extends Ca{};const U=document.getElementById("mys-content");if(U){var X=new ta,Y;Y=new Da(X);var V=new za,Ea=V.g.i,Z=S(X.body,"runtime_data");if(Z){const b=JSON.parse(Z);for(const c in b)b.hasOwnProperty(c)&&Ea.set(c,b[c])}var W,Fa=S(X.body,"render_config")||"[]",C=Fa?JSON.parse(Fa):null;x=C;const a=new ja;x=null;W=a;ya()};}).call(this);
