(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function l(a,b){a=a.split(".");var c=g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var m={},n=null;var p="function"===typeof Uint8Array;const q=Symbol(void 0);function r(a){Object.isFrozen(a)||(q?a[q]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function v(a){return null!==a&&"object"===typeof a&&a.constructor===Object};function w(a,b){if(null!=a)return Array.isArray(a)||v(a)?x(a,b):b(a)}function x(a,b){if(Array.isArray(a)){var c=Array(a.length);for(let e=0;e<a.length;e++)c[e]=w(a[e],b);if(b=Array.isArray(a)){var d;q?d=a[q]:d=a.g;b=(null==d?0:d)&1}b&&r(c);return c}d={};for(c in a)d[c]=w(a[c],b);return d}
function y(a){a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(p&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!n){n={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}b=m[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var t=a[f],u=a[f+
1];k=a[f+2];h=b[t>>2];t=b[(t&3)<<4|u>>4];u=b[(u&15)<<2|k>>6];k=b[k&63];c[e++]=h+t+u+k}h=0;k=d;switch(a.length-f){case 2:h=a[f+1],k=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}a=c.join("")}}return a};let z;function A(a,b,c){var d=z;z=null;a||(a=d);d=this.constructor.o;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.m||0);this.l=null;this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],v(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=null):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.j?(a+=this.i,(d=this.g[a])?Array.isArray(d)&&r(d):this.g[a]=B):(C(this),(d=this.h[a])?Array.isArray(d)&&r(d):this.h[a]=B)}const B=Object.freeze(r([]));
function C(a){let b=a.j+a.i;a.g[b]||(a.h=a.g[b]={})}function D(a,b,c=!1){return-1===b?null:c||b>=a.j?a.h?a.h[b]:void 0:a.g[b+a.i]}function E(a,b){a=D(a,b);return null==a?a:!!a}function F(a,b){a=D(a,b);return null==a?0:a}function G(a){a=E(a,1);return null==a?!1:a}function H(a,b,c){b>=a.j?(C(a),a.h[b]=c):a.g[b+a.i]=c}function I(a,b,c,d){c!==d?H(a,b,c):H(a,b,void 0)}
function J(a,b,c){if(-1===c)return null;a.l||(a.l={});const d=a.l[c];if(d)return d;let e=D(a,c,!1);if(null==e)return d;b=new b(e);return a.l[c]=b}A.prototype.toJSON=function(){return x(this.g,y)};function K(a,b){z=b=b?JSON.parse(b):null;a=new a(b);z=null;return a}A.prototype.toString=function(){return this.g.toString()};var M=class extends A{constructor(a){super(a,-1,L)}},L=[8];var O=class extends A{constructor(a){super(a,-1,N)}},N=[17];var Q=class extends A{constructor(a){super(a,-1,P)}},P=[27];var R=class extends A{constructor(a){super(a)}};var ba=class extends A{constructor(a){super(a,-1,aa)}},aa=[1,2,3];var da=class extends A{constructor(){super(void 0,-1,ca)}},ca=[12];/*

 SPDX-License-Identifier: Apache-2.0
*/
function S(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function T(a,b){a=a.body;var c={detail:void 0};let d;"function"===typeof window.CustomEvent?d=new CustomEvent(b,c):(d=document.createEvent("CustomEvent"),d.initCustomEvent(b,!!c.bubbles,!!c.cancelable,c.detail));a.dispatchEvent(d)}
var ea=class{constructor(a){this.body=a;S(a,"sampling_mod");var b=S(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}addEventListener(a,b){this.body.addEventListener(a,b)}};var fa=class extends A{constructor(){super(void 0)}};function U(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function V(a){if(1>=a.h.offsetWidth||1>=a.h.offsetHeight)return!1;a.g.remove();T(a.context,"spanReady");return!0}
var ha=class{constructor(a,b){this.context=a;this.i=b;this.h=U("SPAN");this.g=U("DIV");this.h.style.fontSize="6px";this.h.textContent="go";this.g.style.position="absolute";this.g.style.top="100%";this.g.style.left="100%";this.g.style.width="1px";this.g.style.height="0";this.g.style.overflow="hidden";this.g.style.visibility="hidden";this.g.appendChild(this.h)}wait(){if(!G(this.i)&&(T(this.context,"spanStart"),this.context.body.appendChild(this.g),!V(this)))return new Promise(a=>{const b=setInterval(()=>
{V(this)&&(clearInterval(b),a())},F(this.i,3))})}};var ia=class{constructor(a,b){this.context=a;this.h=0;this.i=J(b,Q,1);this.g=J(b,M,12)||new M;this.h=a=F(b,2);2===a&&(H(this.g,6,!1),H(this.g,7,!1));J(this.i,O,10)||new O}};var ja=class{constructor(){this.channel=3;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};function W(a){a.g&=-31}function X(a,b){a.g|=b}var ka=class{constructor(a,b){this.context=a;this.j=b;new da;this.g=0;this.pingback=new ja}h(){}};function Y(a){K(ba,S(a.context.body,"engine_msg")||"[]");return a.g.h()||Promise.resolve()}
var la=class{constructor(a,b,c,d){this.g=d(a,b,c);this.context=this.g.context}init(){var a;W(this.g);X(this.g,1);null===(a=window.AFMA_Communicator)||void 0===a?void 0:a.addEventListener("onshow",()=>{X(this.g,32)});let b=0;const c=this.context.body;c.addEventListener("browserRender",()=>{++b;if(1===b)T(this.context,"overallStart"),Y(this).then(()=>{T(this.context,"overallQuiet")});else{var d=c.clientHeight;c.clientWidth&&d&&Y(this)}})}};function ma(a){a.i.length=0;a.h=!0}function Z(a,b){a.g=!0;const c=()=>{a.h=!1;const d=a.i.shift();return void 0===d?(a.g=!1,Promise.resolve()):Z(a,d())};return b?b.then(c,()=>{if(a.h)return c();a.g=!1;return Promise.reject()}):c()}function na(a,b){for(const c of b)a.i.push(c);if(!a.g)return Z(a)}var oa=class{constructor(){this.h=this.g=!1;this.i=[]}};var pa=class extends ka{constructor(){super(...arguments);this.i=new oa}h(){ma(this.i);return na(this.i,[()=>{},()=>{let a;var b=this.j;const c=new fa;I(c,3,100,0);I(c,4,1E4,0);E(b.g,4)?(I(c,6,!0,!1),I(c,7,"monospace",""),I(c,8,"IMWimw0.!?@","")):(E(b.g,5)&&I(c,9,!0,!1),I(c,5,!0,!1));E(b.g,3)&&I(c,2,!0,!1);2===b.h&&I(c,2,!0,!1);c&&(a=(new ha(this.context,c)).wait());T(this.context,"browserStart");T(this.context,"browserStartEnd");W(this);X(this,2);return a},()=>{T(this.context,"browserReady");T(this.context,
"browserReadyEnd");X(this,4);T(this.context,"overallReady")},()=>{T(this.context,"browserQuiet");T(this.context,"browserQuietEnd");X(this,8)}])}};(function(a){let b=null;l("mys.engine.init",(c,d)=>{const e=K(R,S(d,"render_config")||"[]");b=new la(c,d,e,a);b.init()});l("mys.engine.stage",()=>b?b.g.g:0)})(function(a,b,c){a=new ea(b);c=new ia(a,c);return new pa(a,c)});}).call(this);
